name: Builds repos that use Cortex-m-scheduler

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: Javier-varez/google-repo-action@v0.3
      with:
        manifest-url: 'Javier-varez/manifest'
        checkout-deps: true
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.4
      with:
        release: '10-2020-q4'
    - name: Install bear
      run: sudo apt install bear
    - name: Build
      run: make -j
